# Generated by Django 4.2.3 on 2023-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('waiting_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('done', 'done')], default='waiting', max_length=7)),
            ],
        ),
    ]
