# Generated by Django 4.2.3 on 2023-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='waiting_time',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
