# Generated by Django 4.2.3 on 2023-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='waiting_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
