# Generated by Django 4.2.3 on 2023-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('done', 'done')], default='waiting', max_length=7),
        ),
    ]
